print ("Danica A. Oliveria")
print ("Brgy. Botilao, Sta.Cruz, Marinduque")
print ("November 10, 2003")
print ("College of Information and Computing Sciences")
print ("BS Information Technology")
print ("2A")
print ("Playing Volleyball")
print ("Singing")
print ("Dancing")